// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';


function historyReducer(param, action) {
  var stash = param.stash;
  var history = param.history;
  if (typeof action === "number") {
    if (action !== 0) {
      if (stash) {
        return {
                history: {
                  hd: stash.hd,
                  tl: history
                },
                stash: stash.tl
              };
      } else {
        return {
                history: history,
                stash: /* [] */0
              };
      }
    } else if (history) {
      return {
              history: history.tl,
              stash: {
                hd: history.hd,
                tl: stash
              }
            };
    } else {
      return {
              history: /* [] */0,
              stash: stash
            };
    }
  } else {
    return {
            history: {
              hd: action._0,
              tl: history
            },
            stash: stash
          };
  }
}

var historyInit = {
  history: /* [] */0,
  stash: /* [] */0
};

exports.historyInit = historyInit;
exports.historyReducer = historyReducer;
/* No side effect */
